version: "3.1"

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgres
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123445